#! /bin/sh

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         4
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config remove_disabled_monitors true

bspc config focused_border_color '#FFC800'
bspc config normal_border_color '#1E1E1E'

bspc rule -a gamescope state=floating desktop=6

bspc config terminal wezterm

#AutoStart applications
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b &
polybar &
#nitrogen --restore &
hsetroot -solid '#B478FF' &
nm-applet &
blueman-applet &
xmousepasteblock &
copyq &
pgrep light-locker || light-locker &
xautolock -time 10 -locker "light-locker-command -l" &
xfce4-power-manager &

wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle &
wpctl set-volume @DEFAULT_AUDIO_SINK@ 20% &


XDG_MENU_PREFIX=plasma- kbuildsycoca6 &
pcloud &
